### PR TITLE
Fix missing classes same as Sphere, Spline and some methods.

### PR DESCRIPTION
**Pull request by OmidID**
I added `extraClasses` field to CxxBinder.cs which can keep classes who missed.

### CODE REVIEW

**Comment by EgorBo** [comment]
Hey @OmidID thank you for your contribution, unfortunately it's not clear for me what you changed in CxxBinder.cs from the diff - did you change the indention style?

**Comment by OmidID** [comment]
Hi @EgorBo Your welcome. I don't know why it's happen. I used Visual Studio for Mac maybe that why. I can pull it again on Windows and apply changes. Is it OK in this way?

**Comment by OmidID** [comment]
@EgorBo I fixed the problem. I got another clone from original apply changes and push force my old commit.
now you can see the changes.

**Comment by EgorBo** [comment]
LGTM, thank you so much!

**Comment by EgorBo** [comment]
https://www.instagram.com/p/Bi_6_RUlCHk/

**Comment by EgorBo** [comment]
LGTM, thank you so much!

**Comment by OmidID** [comment]
Thank you too ;)

**Pull request merged**
