### PR TITLE
Windows Mixed Reality fixes (including proper x64 support) 

### PR DESCRIPTION
**Pull request by vladkol**
This pull requests depends on another one in Urho3D https://github.com/xamarin/Urho3D/pull/1 
It will not build without Urho3D's one accepted and integrated.

### CODE REVIEW

**Comment by EgorBo** [comment]
Tested on Playgrounds.Tests - works great on both HoloLens and Mixed Reality Portal, awesome!

**Comment by vladkol** [comment]
Yay!

**Comment by EgorBo** [comment]
@vladkol I've pushed UrhoSharp.HoloLens 1.4-alpha to nuget with the MRP support (x86 only, I'll add x64 once I figure out how to configure nuspec to contain both x86 and x64).
Nuget: https://www.nuget.org/packages/UrhoSharp.HoloLens/1.4.0-alpha
Samples are updated and work on both HoloLens and MRP 😃 - https://github.com/xamarin/urho-samples/tree/master/HoloLens

devenv_2017-04-25_17-49-20

**Comment by vladkol** [comment]
Here how they do it https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages 
You also need to use .targets file for referencing VCLib (Microsoft.VCLibs, Version=14.0), this is how you avoid including things like ucrtbased.dll directly into the project. VCLib version conflict and lack of VCLib reference were the reason why it was not working on x64.

**Comment by vladkol** [comment]
This is how UrhoSharp.HoloLens.targets should look like. Build scripts must build x86 and x64 libraries to different directories (e.g HoloLens32 and HoloLens64). Urho.HoloLens.nuspec requires corresponding changes. 
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="CheckNonStoreApp" Condition="'$(WindowsAppContainer)' != 'true'" BeforeTargets="PrepareForBuild">
    <Error Text="Only Universal Windows Apps are supported." />
  </Target>
  <Target Name="CheckAnyCPU" Condition="('$(PlatformTarget)' != 'x86') AND ('$(PlatformTarget)' != 'x64')" BeforeTargets="PrepareForBuild">
    <Error Text="The $(Platform) target platform is not supported." />
  </Target> 
  <ItemGroup Condition=" '$(Platform)' == 'x86' ">
    <Content Include="$(MSBuildThisFileDirectory)\..\..\native\HoloLens32\mono-holourho.dll">
        <Link>mono-holourho.dll</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup Condition=" '$(Platform)' == 'x64' ">
    <Content Include="$(MSBuildThisFileDirectory)\..\..\native\HoloLens64\mono-holourho.dll">
      <Link>mono-holourho.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="$(MSBuildThisFileDirectory)\..\..\native\CoreData.pak">
        <Link>CoreData.pak</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup Condition="'$(ProjectExt)' != '.vcxproj'">
    <SDKReference Include="Microsoft.VCLibs, Version=14.0">
      <Name>Visual C++ 2015 Runtime for Universal Windows Platform Apps</Name>
    </SDKReference>
  </ItemGroup>
</Project>
```

**Comment by EgorBo** [comment]
@vladkol Thanks! Pushed it to the repo. The latest nuget package contains this x64 bit support.
BTW, do you know how can I detect in runtime if an app is executed on:
1) HoloLens
2) VR MR headset
3) Mixed Reality Portal (simulator)
?

**Comment by vladkol** [comment]
@EgorBo I'll check on the emulator. This is how you detect HoloLens 
```cs
            var display = Windows.Graphics.Holographic.HolographicDisplay.GetDefault();
            bool hasVR = display != null;
            if (hasVR)
            {
                bool isHoleLens = !display.IsOpaque;
            }
```

**Comment by EgorBo** [comment]
@vladkol Thanks!

```
	var display = Windows.Graphics.Holographic.HolographicDisplay.GetDefault();
	if (display?.IsOpaque != true)
	{
		var skyboxNode = Scene.CreateChild();
		var skybox = skyboxNode.CreateComponent<Skybox>();
		skybox.Model = CoreAssets.Models.Box; //Sphere
		skybox.SetMaterial(Material.SkyboxFromImage("Textures/Stars.jpg"));
	}

```
improved my HelloWorld sample 😄

**Comment by vladkol** [comment]
@EgorBo IsOpaque is true for VR HMDs, on HoloLens it is false :-)

**Comment by EgorBo** [comment]
@vladkol ah I often confuse 'opaque' and 'transparency' :)

**Comment by vladkol** [comment]
@EgorBo Same with me :-) 
Btw, why is Urho.dll in the HoloLens package? If it must be there, you need to build x64 version too. 
Once we resolve it, x64 configuration can be added to the samples too.

**Comment by EgorBo** [comment]
@vladkol  Are you looking at 1.4.1 ? 1.4.2 has this lib compiled as AnyCPU.
Urho.dll is Urho.HoloLens we use "bait-and-switch" approach so the assemblies should have the same name (PCL + Platform).

**Comment by vladkol** [comment]
Ah, my fault. Updated to 1.4.2, it works great now! Only added x64 project configurations and this to runtimes section in project.json 
    "win10-x64": {},
    "win10-x64-aot": {}

**Comment by EgorBo** [comment]
@vladkol 
I've just updated the VS project template. 
"UrhoSharp For HoloLens" 1.4.5

**Pull request merged**
