### PR TITLE
Add netstandard2.0 support.

### PR DESCRIPTION
**Pull request by andrekoehler**
Nothing special, just created a .NET Standard 2.0 project that has the same content as the PCL.

### CODE REVIEW

**Comment by dotMorten** [comment]
Since you can't actually run on any .NET Standard 2.0 device due to the underlying native pieces, I think this assembly should be compiled as a reference-assembly only, and the NuGet package should ensure that it only allows use in other .NET Standard Libraries, or for TFMs that are supported.

**Comment by andrekoehler** [comment]
@dotMorten 
As far is I understand it, right now the NuGet package already selects the correct library platform for the target project type: https://github.com/xamarin/urho/blob/master/Nuget/Urho.nuspec#L23-L60

**Comment by dotMorten** [comment]
@andrekoehler Yes if the TFM matches, but if it doesn't it falls back to .NET Standard. Ie it'll compile and deploy to Tizen, but then go BOOM at runtime because the native library aren't being deployed.
Same goes for .NETCore which will select NS2.0 but the native code needed to be deployed would be different depending on what OS you'll be executing it on.

**Comment by andrekoehler** [comment]
@dotMorten I understand your point now. As far as I know, a reference assembly does not contain almost not program code, only metadata. All functions return default values or do nothing. I could not find a tutorial on how to build a reference assembly instead of a normal assembly. Even if the NuGet package contained a reference assembly, when this reference assembly is loaded into a project for an unsupported platform, then it will just do nothing. Why is this any better than throwing an exception that tells you the native libraries are missing?

**Comment by dotMorten** [comment]
To produce the ref-assembly, just add this to csproj:
`<ProduceReferenceAssembly>True</ProduceReferenceAssembly>`

> Even if the NuGet package contained a reference assembly, when this reference assembly is loaded into a project for an unsupported platform, then it will just do nothing. Why is this any better than throwing an exception that tells you the native libraries are missing?

This is all about getting compile-time errors. We should be telling the developer up front "hey you can't do that", rather than risk hitting these issues at production time.

**Comment by EgorBo** [comment]
Thank you for your contribution, 
I am reviewing it now.

**Comment by EgorBo** [comment]
Closing since ns2.0 support was added in https://github.com/xamarin/urho/pull/353

**Pull request closed without merging**
